global:
  statReporter:
    enable: false
    plugin:
      prometheus:
        pushgatewayAddress: 127.0.0.1:9091
        pushInterval: 10s
consumer:
  localCache:
    serviceRefreshInterval: 2s