global:
  serverConnectors:
    - protocol: grpc
      addresses:
        - 183.47.111.80:8091
  statReporter:
    enable: false
    plugin:
      prometheus:
        pushgatewayAddress: 127.0.0.1:9091
        pushInterval: 30s
consumer:
  localCache:
    serviceRefreshInterval: 2s